# Replicas of each application
replicaCount: 1

# Domain the application will be served from
dnsName: hershey-park-devapps.redhat-demo.sandbox532.opentlc.com

applications:
  - name: hershey-park-dev
    image: quay.io/rymiller/theme-park-api:hershey-park
